version: '3.1'

services:
  postgres:
    image: postgres:alpine
    container_name: "postgres"
    restart: always
    environment:
      POSTGRES_DB: recall-dev
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    environment:
      SWAGGER_JSON: /swagger.yaml
    ports:
      - "8881:8080"
    volumes:
      - "./swagger.yaml:/swagger.yaml"
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "8882:8080"
